'use strict';

const pages = [
  {
    slug: 'home',
    title: 'Accueil',
    metaTitle: 'Al Manarat Islamiyat',
    metaDescription: 'École islamique moderne à Dakar, dédiée à l’excellence académique et à l’éducation spirituelle.',
    status: 'published',
  },
  {
    slug: 'about',
    title: 'À propos',
    metaTitle: 'À propos de l’école',
    metaDescription: 'Découvrez l’histoire, la mission, la vision, les valeurs et l’équipe de direction d’Al Manarat Islamiyat.',
    status: 'published',
  },
  {
    slug: 'schooling',
    title: 'Scolarité',
    metaTitle: 'Programmes scolaires',
    metaDescription: 'Un parcours scolaire francophone et arabophone structuré, de la maternelle au lycée.',
    status: 'published',
  },
  {
    slug: 'admissions',
    title: 'Admissions',
    metaTitle: 'Admissions 2025-2026',
    metaDescription: 'Procédure d’inscription, pièces à fournir et formulaire de candidature à Al Manarat Islamiyat.',
    status: 'published',
  },
  {
    slug: 'contact',
    title: 'Contact',
    metaTitle: 'Contact',
    metaDescription: 'Contactez l’administration d’Al Manarat Islamiyat pour une visite, une inscription ou une question.',
    status: 'published',
  },
  {
    slug: 'school-access',
    title: 'Espace scolaire',
    metaTitle: 'Accès scolaire GestSchool',
    metaDescription: 'Accès sécurisé à l’espace scolaire GestSchool pour familles, élèves, enseignants et administration.',
    status: 'published',
  },
  { slug: 'news', title: 'Actualités', metaTitle: 'Actualités', status: 'published' },
  { slug: 'events', title: 'Événements', metaTitle: 'Événements', status: 'published' },
  { slug: 'gallery', title: 'Galerie', metaTitle: 'Galerie', status: 'published' },
];

const sections = [
  {
    pageSlug: 'home',
    sectionKey: 'hero',
    type: 'hero',
    title: 'Al Manarat Islamiyat',
    subtitle: 'Excellence académique & formation islamique',
    body: 'Un établissement qui accompagne chaque élève avec exigence, bienveillance et ancrage spirituel.',
    buttons: [
      { label: 'Découvrir l’école', url: '/pages/a-propos.html', variant: 'primary' },
      { label: 'Candidater', url: '/pages/admissions.html', variant: 'secondary' },
    ],
    order: 10,
    visible: true,
  },
  {
    pageSlug: 'home',
    sectionKey: 'about',
    type: 'text-media',
    title: 'Former les leaders de demain',
    subtitle: 'Une école islamique moderne au service du savoir',
    body: 'Bienvenue à l’École Al Manarat Islamiyat, un phare de savoir islamique et d’excellence académique au Sénégal depuis 2005.',
    buttons: [{ label: 'En savoir plus', url: '/pages/a-propos.html', variant: 'primary' }],
    order: 20,
    visible: true,
  },
  {
    pageSlug: 'home',
    sectionKey: 'programs',
    type: 'cards',
    title: 'Nos programmes',
    subtitle: 'Un continuum éducatif cohérent, de la maternelle au lycée.',
    order: 30,
    visible: true,
  },
  {
    pageSlug: 'home',
    sectionKey: 'school-life',
    type: 'cards',
    title: 'Vie scolaire',
    subtitle: 'Des activités spirituelles, culturelles et sportives qui développent l’élève dans toutes ses dimensions.',
    order: 40,
    visible: true,
  },
  {
    pageSlug: 'home',
    sectionKey: 'agenda',
    type: 'list',
    title: 'Agenda',
    subtitle: 'Les prochains rendez-vous importants de l’école.',
    order: 50,
    visible: true,
  },
  {
    pageSlug: 'home',
    sectionKey: 'gallery-preview',
    type: 'media-grid',
    title: 'Galerie',
    subtitle: 'Quelques moments de vie à Al Manarat Islamiyat.',
    order: 60,
    visible: true,
  },
  {
    pageSlug: 'home',
    sectionKey: 'testimonials',
    type: 'quotes',
    title: 'Témoignages',
    subtitle: 'Ce que les familles disent de l’accompagnement Al Manarat.',
    order: 70,
    visible: true,
  },
  {
    pageSlug: 'home',
    sectionKey: 'admissions-cta',
    type: 'cta',
    title: 'Rejoindre Al Manarat',
    subtitle: 'Admissions 2025-2026',
    body: 'Les candidatures sont ouvertes. Déposez votre dossier et échangez avec notre équipe admissions.',
    buttons: [{ label: 'Déposer une candidature', url: '/pages/admissions.html', variant: 'primary' }],
    order: 80,
    visible: true,
  },
  {
    pageSlug: 'home',
    sectionKey: 'contact',
    type: 'contact',
    title: 'Nous contacter',
    subtitle: 'Notre équipe reste disponible pour vous accompagner.',
    order: 90,
    visible: true,
  },

  {
    pageSlug: 'about',
    sectionKey: 'header',
    type: 'page-header',
    title: 'À propos de l’école',
    subtitle: 'Histoire, mission, valeurs et engagement.',
    body: 'Depuis sa création, Al Manarat Islamiyat place l’excellence académique, l’éducation islamique et l’accompagnement humain au cœur de son projet.',
    order: 10,
    visible: true,
  },
  {
    pageSlug: 'about',
    sectionKey: 'history',
    type: 'rich-text',
    title: 'Notre histoire',
    body: [
      'L’École Al Manarat Islamiyat a vu le jour en 2005 à Dakar, portée par une vision éducative islamique moderne : offrir aux familles un cadre exigeant, structuré et bienveillant.',
      'Au fil des années, l’établissement a développé un projet pédagogique qui associe sciences, langues, culture générale, mémorisation et compréhension du Coran, afin de former des élèves équilibrés et responsables.',
      'Aujourd’hui, Al Manarat poursuit son développement avec une organisation plus digitale, un suivi scolaire renforcé et une volonté constante d’améliorer l’expérience des familles.',
    ].join('\n\n'),
    order: 20,
    visible: true,
  },
  {
    pageSlug: 'about',
    sectionKey: 'foundations',
    type: 'cards',
    title: 'Mission, vision & valeurs',
    subtitle: 'Les fondations qui guident notre action éducative.',
    order: 30,
    visible: true,
  },
  {
    pageSlug: 'about',
    sectionKey: 'team',
    type: 'team',
    title: 'La direction',
    subtitle: 'Une équipe dévouée à l’excellence éducative islamique.',
    order: 40,
    visible: true,
  },

  {
    pageSlug: 'schooling',
    sectionKey: 'header',
    type: 'page-header',
    title: 'Nos programmes scolaires',
    subtitle: 'Un parcours académique et islamique complet, de la maternelle au bac.',
    body: 'Al Manarat propose une scolarité organisée autour de parcours francophone et arabophone, avec un suivi pédagogique continu et une attention particulière portée aux apprentissages fondamentaux.',
    order: 10,
    visible: true,
  },
  {
    pageSlug: 'schooling',
    sectionKey: 'curriculum',
    type: 'tabs',
    title: 'Nos niveaux d’enseignement',
    subtitle: 'Des progressions adaptées à chaque âge.',
    order: 20,
    visible: true,
  },
  {
    pageSlug: 'schooling',
    sectionKey: 'orientation',
    type: 'text',
    title: 'Accompagnement et orientation',
    body: 'Chaque élève bénéficie d’un suivi régulier pour consolider ses acquis, préparer les évaluations et construire progressivement son projet scolaire.',
    order: 30,
    visible: true,
  },
  {
    pageSlug: 'schooling',
    sectionKey: 'faq',
    type: 'faq',
    title: 'Questions fréquentes',
    subtitle: 'Les réponses utiles pour comprendre notre organisation scolaire.',
    order: 40,
    visible: true,
  },

  {
    pageSlug: 'admissions',
    sectionKey: 'header',
    type: 'page-header',
    title: 'Admissions 2025-2026',
    subtitle: 'Les inscriptions sont ouvertes.',
    body: 'Notre équipe admissions accompagne chaque famille dans la constitution du dossier, le choix du niveau et les étapes de validation.',
    order: 10,
    visible: true,
  },
  {
    pageSlug: 'admissions',
    sectionKey: 'process',
    type: 'timeline',
    title: 'Étapes de la candidature',
    subtitle: 'Une procédure claire, suivie et transparente.',
    order: 20,
    visible: true,
  },
  {
    pageSlug: 'admissions',
    sectionKey: 'required-documents',
    type: 'checklist',
    title: 'Pièces à fournir',
    subtitle: 'Préparez les documents nécessaires avant de soumettre votre candidature.',
    order: 30,
    visible: true,
  },
  {
    pageSlug: 'admissions',
    sectionKey: 'application-form-intro',
    type: 'form-intro',
    title: 'Formulaire de candidature',
    body: 'Remplissez soigneusement le formulaire. L’administration vous contactera après étude du dossier.',
    order: 40,
    visible: true,
  },

  {
    pageSlug: 'contact',
    sectionKey: 'header',
    type: 'page-header',
    title: 'Contact',
    subtitle: 'Contactez l’administration Al Manarat.',
    body: 'Une question sur les admissions, la scolarité ou le suivi d’un dossier ? Notre équipe est à votre écoute.',
    order: 10,
    visible: true,
  },
  {
    pageSlug: 'contact',
    sectionKey: 'contact-info',
    type: 'contact-info',
    title: 'Coordonnées',
    subtitle: 'Retrouvez les informations pratiques de l’établissement.',
    order: 20,
    visible: true,
  },
  {
    pageSlug: 'contact',
    sectionKey: 'contact-form-intro',
    type: 'form-intro',
    title: 'Envoyer un message',
    body: 'Utilisez le formulaire de contact pour transmettre votre demande à l’administration.',
    order: 30,
    visible: true,
  },

  {
    pageSlug: 'school-access',
    sectionKey: 'header',
    type: 'page-header',
    title: 'Espace scolaire',
    subtitle: 'Accédez à GestSchool avec vos identifiants.',
    body: 'Connectez-vous pour consulter les informations scolaires, administratives et financières liées à votre profil.',
    order: 10,
    visible: true,
  },
  {
    pageSlug: 'school-access',
    sectionKey: 'access-intro',
    type: 'text',
    title: 'Connexion sécurisée',
    body: 'Vos identifiants sont vérifiés par l’API GestSchool. Une fois authentifié, vous êtes redirigé vers votre espace scolaire.',
    order: 20,
    visible: true,
  },
  {
    pageSlug: 'school-access',
    sectionKey: 'gestschool-link',
    type: 'link',
    title: 'GestSchool',
    body: 'Accès réservé aux familles, élèves, enseignants et membres de l’administration.',
    order: 30,
    visible: true,
  },

  { pageSlug: 'news', sectionKey: 'header', type: 'page-header', title: 'Actualités', subtitle: 'Les dernières nouvelles de l’école.', order: 10, visible: true },
  { pageSlug: 'news', sectionKey: 'intro', type: 'text', title: 'Vie de l’établissement', body: 'Retrouvez les informations, annonces et temps forts de l’école.', order: 20, visible: true },
  { pageSlug: 'events', sectionKey: 'header', type: 'page-header', title: 'Événements', subtitle: 'Les rendez-vous importants.', order: 10, visible: true },
  { pageSlug: 'events', sectionKey: 'intro', type: 'text', title: 'Agenda scolaire', body: 'Suivez les événements institutionnels, pédagogiques et communautaires.', order: 20, visible: true },
  { pageSlug: 'gallery', sectionKey: 'header', type: 'page-header', title: 'Galerie', subtitle: 'Images et souvenirs de l’école.', order: 10, visible: true },
  { pageSlug: 'gallery', sectionKey: 'intro', type: 'text', title: 'Moments de vie', body: 'Découvrez quelques images de la vie scolaire et des activités de l’établissement.', order: 20, visible: true },
];

const blocks = [
  { pageSlug: 'home', sectionKey: 'programs', type: 'program', title: 'Maternelle', body: 'Éveil, langage, motricité, socialisation et premiers repères islamiques.', icon: 'sprout', order: 10, visible: true },
  { pageSlug: 'home', sectionKey: 'programs', type: 'program', title: 'Primaire', body: 'Fondamentaux solides en français, mathématiques, arabe, Coran et découverte du monde.', icon: 'book-open', order: 20, visible: true },
  { pageSlug: 'home', sectionKey: 'programs', type: 'program', title: 'Collège', body: 'Méthodes de travail, culture générale, sciences, langues et suivi disciplinaire renforcé.', icon: 'graduation-cap', order: 30, visible: true },
  { pageSlug: 'home', sectionKey: 'programs', type: 'program', title: 'Lycée', body: 'Préparation aux examens, orientation et accompagnement vers l’enseignement supérieur.', icon: 'award', order: 40, visible: true },

  { pageSlug: 'home', sectionKey: 'school-life', type: 'activity', title: 'Prières et rappels', body: 'Un cadre spirituel vivant, adapté au rythme scolaire.', icon: 'mosque', order: 10, visible: true },
  { pageSlug: 'home', sectionKey: 'school-life', type: 'activity', title: 'Clubs et ateliers', body: 'Lecture, sciences, langues, expression orale et créativité.', icon: 'sparkles', order: 20, visible: true },
  { pageSlug: 'home', sectionKey: 'school-life', type: 'activity', title: 'Activités sportives', body: 'Développement de l’esprit d’équipe et de la discipline.', icon: 'activity', order: 30, visible: true },
  { pageSlug: 'home', sectionKey: 'school-life', type: 'activity', title: 'Sorties pédagogiques', body: 'Des expériences concrètes pour relier apprentissages et réalité.', icon: 'map', order: 40, visible: true },

  { pageSlug: 'home', sectionKey: 'testimonials', type: 'quote', title: 'Parent d’élève', body: 'Nous apprécions le sérieux du suivi et l’équilibre entre enseignement général et valeurs islamiques.', order: 10, visible: true },
  { pageSlug: 'home', sectionKey: 'testimonials', type: 'quote', title: 'Ancien élève', body: 'Al Manarat m’a donné des bases solides, de la méthode et le goût de l’effort.', order: 20, visible: true },
  { pageSlug: 'home', sectionKey: 'testimonials', type: 'quote', title: 'Enseignante', body: 'L’équipe avance avec une vraie ambition pédagogique et beaucoup d’attention pour les élèves.', order: 30, visible: true },

  { pageSlug: 'about', sectionKey: 'foundations', type: 'value', title: 'Notre Mission', body: 'Former des citoyens exemplaires, ancrés dans les valeurs islamiques et capables de réussir dans le monde contemporain.', icon: 'target', order: 10, visible: true },
  { pageSlug: 'about', sectionKey: 'foundations', type: 'value', title: 'Notre Vision', body: 'Devenir une référence régionale de l’éducation islamique moderne, exigeante et ouverte sur son environnement.', icon: 'compass', order: 20, visible: true },
  { pageSlug: 'about', sectionKey: 'foundations', type: 'value', title: 'Nos Valeurs', body: 'Excellence, intégrité, respect, responsabilité, bienveillance et amour du savoir.', icon: 'gem', order: 30, visible: true },
  { pageSlug: 'about', sectionKey: 'team', type: 'team-member', title: 'Sheikh Diallo Fodé', subtitle: 'Directeur Général', order: 10, visible: true, metadata: { initials: 'DF', color: '#059669' } },
  { pageSlug: 'about', sectionKey: 'team', type: 'team-member', title: 'Mme Aïssatou Camara', subtitle: 'Directrice Pédagogique', order: 20, visible: true, metadata: { initials: 'AC', color: '#d97706' } },
  { pageSlug: 'about', sectionKey: 'team', type: 'team-member', title: 'M. Mamadou Diop', subtitle: 'Responsable Département Arabe', order: 30, visible: true, metadata: { initials: 'MD', color: '#3b82f6' } },
  { pageSlug: 'about', sectionKey: 'team', type: 'team-member', title: 'Mme Fatou Sow', subtitle: 'Responsable des Admissions', order: 40, visible: true, metadata: { initials: 'FS', color: '#7c3aed' } },

  { pageSlug: 'schooling', sectionKey: 'curriculum', type: 'level', title: 'Maternelle', body: 'Développement du langage, autonomie, éveil religieux, motricité et socialisation.', order: 10, visible: true },
  { pageSlug: 'schooling', sectionKey: 'curriculum', type: 'level', title: 'Élémentaire', body: 'Français, mathématiques, arabe, Coran, découverte du monde et méthodes de travail.', order: 20, visible: true },
  { pageSlug: 'schooling', sectionKey: 'curriculum', type: 'level', title: 'Collège', body: 'Renforcement académique, sciences, langues, culture islamique et préparation aux examens.', order: 30, visible: true },
  { pageSlug: 'schooling', sectionKey: 'curriculum', type: 'level', title: 'Lycée', body: 'Orientation, approfondissement disciplinaire et préparation aux études supérieures.', order: 40, visible: true },
  { pageSlug: 'schooling', sectionKey: 'faq', type: 'faq-item', title: 'Quels cursus sont proposés ?', body: 'L’établissement organise des parcours francophone et arabophone, avec des passerelles selon les niveaux.', order: 10, visible: true },
  { pageSlug: 'schooling', sectionKey: 'faq', type: 'faq-item', title: 'Le Coran est-il intégré au programme ?', body: 'Oui. Le suivi coranique et l’éducation islamique sont intégrés dans l’organisation pédagogique.', order: 20, visible: true },
  { pageSlug: 'schooling', sectionKey: 'faq', type: 'faq-item', title: 'Comment les familles suivent-elles la scolarité ?', body: 'Le suivi est assuré par l’administration, les enseignants et l’espace scolaire GestSchool.', order: 30, visible: true },

  { pageSlug: 'admissions', sectionKey: 'process', type: 'step', title: 'Pré-demande', body: 'La famille renseigne les informations principales de l’enfant et du responsable.', order: 10, visible: true },
  { pageSlug: 'admissions', sectionKey: 'process', type: 'step', title: 'Étude du dossier', body: 'L’administration vérifie les pièces et confirme le niveau demandé.', order: 20, visible: true },
  { pageSlug: 'admissions', sectionKey: 'process', type: 'step', title: 'Entretien ou test', body: 'Selon le niveau, un entretien ou une évaluation peut être proposé.', order: 30, visible: true },
  { pageSlug: 'admissions', sectionKey: 'process', type: 'step', title: 'Validation', body: 'Après acceptation, l’inscription est finalisée par l’administration.', order: 40, visible: true },
  { pageSlug: 'admissions', sectionKey: 'required-documents', type: 'document', title: 'Extrait de naissance', order: 10, visible: true },
  { pageSlug: 'admissions', sectionKey: 'required-documents', type: 'document', title: 'Bulletins ou relevés récents', order: 20, visible: true },
  { pageSlug: 'admissions', sectionKey: 'required-documents', type: 'document', title: 'Photo d’identité', order: 30, visible: true },
  { pageSlug: 'admissions', sectionKey: 'required-documents', type: 'document', title: 'Pièce d’identité du responsable', order: 40, visible: true },
  { pageSlug: 'admissions', sectionKey: 'required-documents', type: 'document', title: 'Certificat de scolarité si disponible', order: 50, visible: true },

  { pageSlug: 'contact', sectionKey: 'contact-info', type: 'contact-item', title: 'Adresse', body: 'Dakar, Sénégal', icon: 'map-pin', order: 10, visible: true },
  { pageSlug: 'contact', sectionKey: 'contact-info', type: 'contact-item', title: 'Téléphone', body: '+221 77 000 00 00', icon: 'phone', order: 20, visible: true },
  { pageSlug: 'contact', sectionKey: 'contact-info', type: 'contact-item', title: 'Email', body: 'contact@almanarat.sn', icon: 'mail', order: 30, visible: true },
  { pageSlug: 'contact', sectionKey: 'contact-info', type: 'contact-item', title: 'Horaires', body: 'Lundi au vendredi, 8h00 - 17h00', icon: 'clock', order: 40, visible: true },
];

const navigation = [
  { label: 'Accueil', url: '/index.html', order: 10, visible: true, type: 'main' },
  { label: 'À propos', url: '/pages/a-propos.html', order: 20, visible: true, type: 'main' },
  { label: 'Scolarité', url: '/pages/scolarite.html', order: 30, visible: true, type: 'main' },
  { label: 'Admissions', url: '/pages/admissions.html', order: 40, visible: true, type: 'main' },
  { label: 'Actualités', url: '/pages/actualites.html', order: 50, visible: true, type: 'main' },
  { label: 'Événements', url: '/pages/evenements.html', order: 60, visible: true, type: 'main' },
  { label: 'Galerie', url: '/pages/galerie.html', order: 70, visible: true, type: 'main' },
  { label: 'Contact', url: '/pages/contact.html', order: 80, visible: true, type: 'main' },
  { label: 'Espace Scolaire', url: '/acces-scolaire', order: 90, visible: true, type: 'main' },
];

const footer = [
  {
    columnKey: 'brand',
    title: 'Al Manarat Islamiyat',
    content: 'Une école islamique d’excellence au service du savoir, de l’éducation et de la réussite des élèves.',
    order: 10,
    visible: true,
  },
  {
    columnKey: 'quick-links',
    title: 'Liens rapides',
    links: [
      { label: 'À propos', url: '/pages/a-propos.html' },
      { label: 'Scolarité', url: '/pages/scolarite.html' },
      { label: 'Admissions', url: '/pages/admissions.html' },
      { label: 'Actualités', url: '/pages/actualites.html' },
      { label: 'Contact', url: '/pages/contact.html' },
    ],
    order: 20,
    visible: true,
  },
  {
    columnKey: 'contact',
    title: 'Contact',
    content: 'Dakar, Sénégal\n+221 77 000 00 00\ncontact@almanarat.sn',
    order: 30,
    visible: true,
  },
];

const media = [];

module.exports = {
  blocks,
  footer,
  media,
  navigation,
  pages,
  sections,
};
